export const cityAliases: Record<string, string[]> = {
  ahmedabad: ['ahmadabad', 'ahmedabad'],
  bangalore: ['bengaluru', 'bangalore'],
  bhopal: ['bhopal'],
  calcutta: ['kolkata', 'calcutta'],
  chennai: ['chennai', 'madras'],
  delhi: ['new delhi', 'delhi'],
  hyderabad: ['hyderabad'],
  indore: ['indore'],
  jaipur: ['jaipur'],
  kochi: ['kochi', 'cochin'],
  lucknow: ['lucknow'],
  mumbai: ['mumbai', 'bombay'],
  nagpur: ['nagpur'],
  pune: ['pune'],
  surat: ['surat'],
};
