import React from 'react';
import {
    AlertCircle,
    AlertTriangle,
    ArrowLeft,
    ArrowRight,
    ArrowUpDown,
    Award,
    Banknote,
    BarChart3,
    Bell,
    BetweenHorizontalEnd,
    Book,
    Briefcase,
    Building,
    Building2,
    Cake,
    Calendar,
    Camera,
    Check,
    CheckCircle,
    ChefHat,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    Clipboard,
    Clock,
    Coffee,
    CreditCard,
    Crown,
    Database,
    DollarSign,
    Download,
    EggFried,
    ExternalLink,
    Eye,
    EyeOff,
    Facebook,
    FileText,
    Filter,
    Gift,
    Grid3X3,
    Grid3x2,
    Handshake,
    Headphones,
    Heart,
    HelpCircle,
    Home,
    IndianRupee,
    Info,
    Instagram,
    Leaf,
    Linkedin,
    List,
    LocateFixed,
    LocateIcon,
    Lock,
    LogIn,
    LogInIcon,
    LogOut,
    LogOutIcon,
    LucideEdit3,
    LucideTrash2,
    Mail,
    MapPin,
    Menu,
    MessageCircle,
    Minus,
    Navigation,
    Newspaper,
    Package,
    Paperclip,
    Percent,
    Phone,
    PizzaIcon,
    Play,
    Plus,
    QrCode,
    Receipt,
    RefreshCw,
    RotateCcw,
    Salad,
    Sandwich,
    Save,
    Search,
    Send,
    Settings,
    Shield,
    ShoppingBag,
    ShoppingCart,
    Smartphone,
    Sparkles,
    Star,
    Store,
    Tag,
    ThumbsDown,
    ThumbsUp,
    Timer,
    Trash,
    Trash2,
    TrendingUp,
    Truck,
    Twitter,
    User,
    Users2,
    Video,
    Wallet,
    X,
    XCircle,
    Youtube,
    Zap,
    FireExtinguisherIcon,
} from 'lucide-react';
import { LucideProps } from 'lucide-react';

const iconMap = {
    'bank-note': Banknote,
    'chevron-left': ChevronLeft,
    'chevron-right': ChevronRight,
    search: Search,
    'shopping-cart': ShoppingCart,
    user: User,
    'map-pin': MapPin,
    star: Star,
    heart: Heart,
    bell: Bell,
    home: Home,
    menu: Menu,
    x: X,
    'check-circle': CheckCircle,
    'alert-circle': AlertCircle,
    clock: Clock,
    tag: Tag,
    building2: Building2,
    'chevron-down': ChevronDown,
    facebook: Facebook,
    instagram: Instagram,
    twitter: Twitter,
    linkedin: Linkedin,
    youtube: Youtube,
    'arrow-left': ArrowLeft,
    'credit-card': CreditCard,
    settings: Settings,
    'help-circle': HelpCircle,
    logout: LogOut,
    'shopping-bag': ShoppingBag,
    eye: Eye,
    'eye-off': EyeOff,
    mail: Mail,
    lock: Lock,
    'arrow-right': ArrowRight,
    truck: Truck,
    plus: Plus,
    minus: Minus,
    'trash-2': Trash2,
    info: Info,
    building: Building,
    'rotate-ccw': RotateCcw,
    store: Store,
    filter: Filter,
    check: Check,
    zap: Zap,
    'trending-up': TrendingUp,
    award: Award,
    shield: Shield,
    'bar-chart-3': BarChart3,
    coffee: Coffee,
    play: Play,
    headphones: Headphones,
    gift: Gift,
    'users-2': Users2,
    users: User,
    'building-2': Building2,
    briefcase: Briefcase,
    newspaper: Newspaper,
    login: LogIn,
    percent: Percent,
    crown: Crown,
    pizza: PizzaIcon,
    sandwich: Sandwich,
    'egg-fried': EggFried,
    cake: Cake,
    leaf: Leaf,
    fire: FireExtinguisherIcon,
    clipboard: Clipboard,
    'lucide-edit-3': LucideEdit3,
    'lucide-trash-2': LucideTrash2,
    camera: Camera,
    save: Save,
    'grid-3x3': Grid3X3,
    list: List,
    'message-circle': MessageCircle,
    phone: Phone,
    send: Send,
    'paper-clip': Paperclip,
    'thumbs-up': ThumbsUp,
    'thumbs-down': ThumbsDown,
    book: Book,
    'file-text': FileText,
    video: Video,
    'external-link': ExternalLink,
    package: Package,
    'chevron-up': ChevronUp,
    'x-circle': XCircle,
    calendar: Calendar,
    navigation: Navigation,
    receipt: Receipt,
    'dollar-sign': DollarSign,
    download: Download,
    wallet: Wallet,
    'alert-triangle': AlertTriangle,
    'refresh-cw': RefreshCw,
    database: Database,
    sparkles: Sparkles,
    timer: Timer,
    salad: Salad,
    'indian-rupee': IndianRupee,
    trash: Trash,
    'between-horizontal-end': BetweenHorizontalEnd,
    'chef-hat': ChefHat,
    grid3x2: Grid3x2,
    smartphone: Smartphone,
    'log-out': LogOutIcon,
    'log-in': LogInIcon,
    'location-pin': LocateIcon,
    handshake: Handshake,
    'locate-fixed': LocateFixed,
    'arrow-up-down': ArrowUpDown,
    'qr-code': QrCode,
} as const;

export type IconName = keyof typeof iconMap;

interface IconProps extends LucideProps {
    name: IconName | string;
    size?: number | string;
    color?: string;
    className?: string;
}

const Icon: React.FC<IconProps> = ({
    name,
    size = 20,
    color = 'currentColor',
    className = '',
    ...props
}) => {
    const LucideIconComponent = iconMap[name.toLowerCase() as IconName];

    if (!LucideIconComponent) {
        if (process.env.NODE_ENV === 'development') {
            console.warn(
                `Icon "${name}" not found or not mapped. Please add it to the 'iconMap'.`
            );
        }
        return null;
    }

    return (
        <LucideIconComponent
            size={size}
            color={color}
            className={className}
            {...props}
        />
    );
};

export default Icon;
